[package]
name = "apppw-windows"
version = "0.1.0"
edition = "2024"

[dependencies]
apppw-core = { path = "../apppw-core" }
windows = { version = "0.62.2", features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Threading",
	"Win32_Graphics_Gdi",
	"Win32_Storage_FileSystem",
	"Win32_UI_Shell",
	"Win32_UI_WindowsAndMessaging",
	"Win32_NetworkManagement",
	"Win32_NetworkManagement_IpHelper",
	"Win32_Networking",
	"Win32_Networking_WinSock",
] }
