use crate::domain::{EventKind, NetworkEvent, Process};

pub fn demo_processes() -> Vec<Process> {
    vec![
        Process {
            pid: 14_280,
            name: "Discord.exe",
            active: true,
        },
        Process {
            pid: 9_404,
            name: "Steam.exe",
            active: true,
        },
        Process {
            pid: 22_116,
            name: "firefox.exe",
            active: true,
        },
        Process {
            pid: 6_732,
            name: "Game.exe",
            active: true,
        },
        Process {
            pid: 3_188,
            name: "Code.exe",
            active: false,
        },
        Process {
            pid: 1_064,
            name: "Spotify.exe",
            active: true,
        },
    ]
}

pub fn demo_events() -> Vec<NetworkEvent> {
    vec![
        NetworkEvent {
            id: 1,
            pid: 14_280,
            process: "Discord.exe",
            method: "GET",
            host: "discord.com",
            path: "/api/v10/users/@me",
            status: Some(200),
            kind: EventKind::Https,
            sent: "412 B",
            received: "2.3 KB",
            duration_ms: Some(74),
            local: "192.168.1.10:53142",
            remote: "162.159.135.232:443",
        },
        NetworkEvent {
            id: 2,
            pid: 14_280,
            process: "Discord.exe",
            method: "POST",
            host: "discord.com",
            path: "/api/v10/channels/123/messages",
            status: Some(200),
            kind: EventKind::Https,
            sent: "428 B",
            received: "512 B",
            duration_ms: Some(91),
            local: "192.168.1.10:53146",
            remote: "162.159.135.232:443",
        },
        NetworkEvent {
            id: 3,
            pid: 14_280,
            process: "Discord.exe",
            method: "TLS",
            host: "gateway.discord.gg",
            path: "",
            status: None,
            kind: EventKind::Tls,
            sent: "3.1 KB",
            received: "8.4 KB",
            duration_ms: None,
            local: "192.168.1.10:53151",
            remote: "162.159.130.234:443",
        },
        NetworkEvent {
            id: 4,
            pid: 14_280,
            process: "Discord.exe",
            method: "UDP",
            host: "162.159.130.234",
            path: "",
            status: None,
            kind: EventKind::Udp,
            sent: "3.2 KB",
            received: "1.1 KB",
            duration_ms: None,
            local: "192.168.1.10:52111",
            remote: "162.159.130.234:50000",
        },
        NetworkEvent {
            id: 5,
            pid: 9_404,
            process: "Steam.exe",
            method: "TCP",
            host: "cm0.steampowered.com",
            path: "",
            status: None,
            kind: EventKind::Tcp,
            sent: "8.7 KB",
            received: "22.1 KB",
            duration_ms: None,
            local: "192.168.1.10:53310",
            remote: "162.254.197.40:27017",
        },
        NetworkEvent {
            id: 6,
            pid: 22_116,
            process: "firefox.exe",
            method: "GET",
            host: "example.com",
            path: "/api/health",
            status: Some(204),
            kind: EventKind::Http,
            sent: "288 B",
            received: "0 B",
            duration_ms: Some(38),
            local: "192.168.1.10:53402",
            remote: "93.184.216.34:80",
        },
        NetworkEvent {
            id: 7,
            pid: 6_732,
            process: "Game.exe",
            method: "QUIC",
            host: "51.89.14.20",
            path: "",
            status: None,
            kind: EventKind::Quic,
            sent: "12.4 KB",
            received: "36.9 KB",
            duration_ms: None,
            local: "192.168.1.10:54001",
            remote: "51.89.14.20:443",
        },
        NetworkEvent {
            id: 8,
            pid: 3_188,
            process: "Code.exe",
            method: "TCP",
            host: "185.199.108.133",
            path: "",
            status: None,
            kind: EventKind::Unknown,
            sent: "164 B",
            received: "92 B",
            duration_ms: None,
            local: "192.168.1.10:54492",
            remote: "185.199.108.133:9000",
        },
        NetworkEvent {
            id: 9,
            pid: 1_064,
            process: "Spotify.exe",
            method: "GET",
            host: "api-partner.spotify.com",
            path: "/pathfinder/v1/query",
            status: Some(200),
            kind: EventKind::Https,
            sent: "1.2 KB",
            received: "6.8 KB",
            duration_ms: Some(63),
            local: "192.168.1.10:54580",
            remote: "35.186.224.25:443",
        },
    ]
}
